Repository team-forAdhd/forAdhd-server, pull requests merged in 2024-09, with the labels that each got.

#46 병원, 의사 CSV → DB에 저장, 수정, 삭제 로직 구현
  .gitignore
  build.gradle
  src/main/java/com/project/foradhd/domain/hospital/persistence/entity/Hospital.java
  src/main/java/com/project/foradhd/global/client/GooglePlacesClient.java
  src/main/java/com/project/foradhd/global/client/config/GooglePlacesClientConfig.java
  src/main/java/com/project/foradhd/global/client/dto/response/GooglePlaceListResponse.java
  src/main/java/com/project/foradhd/global/data/hospital/HospitalCsvProcessor.java
  src/main/java/com/project/foradhd/global/util/CSVUtil.java
  src/main/java/com/project/foradhd/global/util/StringUtil.java
  src/main/resources/application.yml
  src/test/java/com/project/foradhd/global/util/StringUtilTest.java
Labels: D-3

#54 테스트 코드 작성 및 리팩토링
  src/main/java/com/project/foradhd/domain/auth/business/service/AuthService.java
  src/main/java/com/project/foradhd/domain/auth/business/service/OAuth2UserInfoService.java
  src/main/java/com/project/foradhd/domain/auth/business/service/impl/AuthServiceImpl.java
  src/main/java/com/project/foradhd/domain/auth/business/service/impl/JwtServiceImpl.java
  src/main/java/com/project/foradhd/domain/auth/business/service/impl/OAuth2UserInfoServiceImpl.java
  src/main/java/com/project/foradhd/domain/auth/web/dto/request/TokenReissueRequest.java
  src/main/java/com/project/foradhd/domain/hospital/business/service/HospitalOperationService.java
  src/main/java/com/project/foradhd/domain/hospital/business/service/HospitalService.java
  src/main/java/com/project/foradhd/domain/hospital/business/service/impl/HospitalOperationServiceImpl.java
  src/main/java/com/project/foradhd/domain/hospital/business/service/impl/HospitalServiceImpl.java
  src/main/java/com/project/foradhd/domain/hospital/web/dto/request/HospitalEvaluationReviewCreateRequest.java
  src/main/java/com/project/foradhd/domain/hospital/web/dto/request/HospitalEvaluationReviewUpdateRequest.java
  src/main/java/com/project/foradhd/domain/hospital/web/dto/request/HospitalReceiptReviewCreateRequest.java
  src/main/java/com/project/foradhd/domain/hospital/web/dto/request/HospitalReceiptReviewUpdateRequest.java
  src/main/java/com/project/foradhd/domain/user/business/dto/out/UserProfileDetailsData.java
  src/main/java/com/project/foradhd/domain/user/business/service/UserEmailAuthService.java
  src/main/java/com/project/foradhd/domain/user/business/service/UserService.java
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserEmailAuthServiceImpl.java
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/EmailAuthRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/EmailAuthValidationRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/NicknameCheckRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/PasswordUpdateRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/ProfileUpdateRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/PushNotificationApprovalUpdateRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/SnsSignUpRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/TermsApprovalsUpdateRequest.java
  src/main/java/com/project/foradhd/global/enums/CacheKeyType.java
  src/main/java/com/project/foradhd/global/image/web/controller/FileUploadController.java
  src/main/java/com/project/foradhd/global/service/CacheService.java
  src/main/java/com/project/foradhd/global/service/EmailService.java
  src/main/java/com/project/foradhd/global/service/FileStorageService.java
  src/main/java/com/project/foradhd/global/service/impl/AwsS3Service.java
  src/main/java/com/project/foradhd/global/service/impl/AwsSesService.java
  src/main/java/com/project/foradhd/global/service/impl/RedisService.java
  src/main/java/com/project/foradhd/global/util/JsonUtil.java
  src/test/java/com/project/foradhd/config/SecurityControllerTestConfig.java
  src/test/java/com/project/foradhd/config/SecurityTestConfig.java
  src/test/java/com/project/foradhd/config/user/WithMockTestUser.java
  src/test/java/com/project/foradhd/config/user/WithMockTestUserSecurityContextFactory.java
  src/test/java/com/project/foradhd/domain/auth/business/service/AuthServiceTest.java
  src/test/java/com/project/foradhd/domain/auth/web/controller/AuthControllerTest.java
  src/test/java/com/project/foradhd/domain/auth/web/controller/SecurityFilterTest.java
  src/test/java/com/project/foradhd/domain/hospital/business/service/HospitalServiceTest.java
  src/test/java/com/project/foradhd/domain/hospital/web/controller/HospitalControllerTest.java
  src/test/java/com/project/foradhd/domain/user/business/service/UserEmailAuthServiceTest.java
  src/test/java/com/project/foradhd/domain/user/business/service/UserServiceTest.java
  src/test/java/com/project/foradhd/domain/user/web/controller/UserControllerTest.java
  src/test/java/com/project/foradhd/global/service/RedisServiceTest.java
  src/test/resources/application.yml
Labels: D-3

#53 약 리뷰 레포지토리 쿼리 수정
  src/main/java/com/project/foradhd/domain/medicine/business/service/Impl/MedicineReviewServiceImpl.java
  src/main/java/com/project/foradhd/domain/medicine/business/service/MedicineReviewService.java
  src/main/java/com/project/foradhd/domain/medicine/persistence/repository/MedicineReviewRepository.java
  src/main/java/com/project/foradhd/domain/medicine/web/controller/MedicineReviewController.java
  src/main/java/com/project/foradhd/domain/medicine/web/mapper/MedicineReviewMapper.java
  src/test/java/com/project/foradhd/domain/medicine/business/service/Impl/MedicineBookmarkServiceImplTest.java
  src/test/java/com/project/foradhd/domain/medicine/business/service/Impl/MedicineReviewServiceImplTest.java
  src/test/java/com/project/foradhd/domain/medicine/business/service/Impl/MedicineServiceImplTest.java
Labels: D-4

#56 소셜 로그인 키 관리 방식 변경
  src/main/java/com/project/foradhd/global/client/config/GooglePlacesClientConfig.java
  src/main/resources/application-oauth2.yml
  src/main/resources/application.yml
Labels: D-5

#58 유저 이메일 중복 여부 확인 api 개발
  src/main/java/com/project/foradhd/domain/user/business/dto/out/UserTokenData.java
  src/main/java/com/project/foradhd/domain/user/business/service/UserEmailAuthService.java
  src/main/java/com/project/foradhd/domain/user/business/service/UserService.java
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserEmailAuthServiceImpl.java
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java
  src/main/java/com/project/foradhd/domain/user/web/controller/UserController.java
  src/main/java/com/project/foradhd/domain/user/web/dto/request/EmailCheckRequest.java
  src/main/java/com/project/foradhd/domain/user/web/dto/response/EmailCheckResponse.java
  src/main/java/com/project/foradhd/domain/user/web/mapper/UserMapper.java
  src/main/java/com/project/foradhd/global/config/SecurityConfig.java
  src/test/java/com/project/foradhd/domain/user/business/service/UserEmailAuthServiceTest.java
  src/test/java/com/project/foradhd/domain/user/business/service/UserServiceTest.java
  src/test/java/com/project/foradhd/domain/user/web/controller/UserControllerTest.java
Labels: D-1

#60 애플 로그인 시 CORS 에러 해결
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/web/controller/NotificationController.java
  src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java
  src/main/java/com/project/foradhd/global/config/SecurityConfig.java
  src/main/java/com/project/foradhd/global/config/WebConfig.java
  src/main/resources/application.yml
Labels: D-2
