Repository team-forAdhd/forAdhd-server, pull requests merged in 2025-02, with the labels that each got.

#104 유저 역할 조회 기능 구현
  src/main/java/com/project/foradhd/domain/user/business/dto/out/UserProfileDetailsData.java
  src/main/java/com/project/foradhd/domain/user/business/service/UserService.java
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java
  src/main/java/com/project/foradhd/domain/user/web/dto/response/UserProfileDetailsResponse.java
  src/main/java/com/project/foradhd/domain/user/web/mapper/UserMapper.java
Labels: D-0

#105 신고기능 구현
  src/main/java/com/project/foradhd/ForadhdApplication.java
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostReportServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/business/service/PostReportService.java
  src/main/java/com/project/foradhd/domain/board/business/service/dto/in/ReportPostData.java
  src/main/java/com/project/foradhd/domain/board/persistence/entity/ReportPost.java
  src/main/java/com/project/foradhd/domain/board/persistence/enums/HandleReport.java
  src/main/java/com/project/foradhd/domain/board/persistence/enums/Report.java
  src/main/java/com/project/foradhd/domain/board/persistence/repository/ReportPostRepository.java
  src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
  src/main/java/com/project/foradhd/domain/board/web/dto/response/PostReportListResponseDto.java
  src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java
  src/main/java/com/project/foradhd/domain/user/business/service/UserService.java
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java
  src/main/java/com/project/foradhd/domain/user/persistence/entity/User.java
  src/main/java/com/project/foradhd/domain/user/persistence/repository/UserRepository.java
Labels: D-1

#107 Role 반환 Mapping 작성 및 유저 Birth필드 추가로 반환
  src/main/java/com/project/foradhd/domain/user/business/dto/out/UserProfileDetailsData.java
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java
  src/main/java/com/project/foradhd/domain/user/web/dto/response/UserProfileDetailsResponse.java
  src/main/java/com/project/foradhd/domain/user/web/mapper/UserMapper.java
Labels: D-3

#110 fix: 게시글 스크랩 및 좋아요 기능 스위칭 에러 해결
  .DS_Store
  src/main/java/com/project/foradhd/domain/board/persistence/entity/PostLikeFilter.java
  src/main/java/com/project/foradhd/domain/board/persistence/entity/PostScrapFilter.java
Labels: D-2
