Repository team-forAdhd/forAdhd-server, pull requests merged in 2025-04, with the labels that each got.

#166 feat: SSE 기반 알림 기능 구현 및 알림 읽음 처리 추가
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/NotificationServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/persistence/entity/Notification.java
  src/main/java/com/project/foradhd/domain/board/persistence/repository/NotificationRepository.java
  src/main/java/com/project/foradhd/domain/board/web/controller/NotificationController.java
  src/main/java/com/project/foradhd/domain/board/web/dto/response/NotificationResponse.java
  src/main/java/com/project/foradhd/domain/board/web/mapper/NotificationMapper.java
Labels: D-5

#169 fix: 비밀번호 특수문자 수정
  src/main/java/com/project/foradhd/global/validation/validator/PasswordValidator.java
Labels: D-1

#170 신고 당한 게시글 내역 조회 쿼리 개선
  src/main/java/com/project/foradhd/domain/board/persistence/repository/ReportPostRepository.java
Labels: D-5

#172 mod: 약 리뷰 조회 시 작성자 확인 필드 추가
  src/main/java/com/project/foradhd/domain/medicine/business/service/impl/MedicineReviewServiceImpl.java
  src/main/java/com/project/foradhd/domain/medicine/persistence/repository/MedicineReviewLikeRepository.java
  src/main/java/com/project/foradhd/domain/medicine/persistence/repository/MedicineReviewRepository.java
  src/main/java/com/project/foradhd/domain/medicine/web/controller/MedicineReviewController.java
  src/main/java/com/project/foradhd/domain/medicine/web/dto/response/MedicineReviewResponse.java
  src/main/java/com/project/foradhd/domain/medicine/web/mapper/MedicineReviewMapper.java
Labels: D-2

#180 feat: prometheus 설정
  build.gradle
  src/main/resources/application.yml
Labels: D-5

#191 chore: prometheus 경로 인증 제외 설정
  src/main/java/com/project/foradhd/global/config/SecurityConfig.java
Labels: D-0

#189 bugfix: 일부 전화번호 데이터가 비어있는 병원 로딩 에러 수정
  src/main/java/com/project/foradhd/global/serializer/PhoneSerializer.java
Labels: D-1
