Repository team-forAdhd/forAdhd-server, pull requests merged in 2025-03, with the labels that each got.

#112 fix: 게시글 신고 API 신고 유형 값 받을 때 DTO를 통한 매핑으로 받을 수 있도록 수정
  src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
  src/main/java/com/project/foradhd/domain/board/web/dto/request/ReportTypeDto.java
Labels: D-0

#114 feat: 게시글 및 댓글 작성자 표시
  .DS_Store
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostLikeFilterServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostScrapFilterServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/business/service/PostLikeFilterService.java
  src/main/java/com/project/foradhd/domain/board/business/service/PostScrapFilterService.java
  src/main/java/com/project/foradhd/domain/board/persistence/repository/PostScrapFilterRepository.java
  src/main/java/com/project/foradhd/domain/board/web/controller/CommentController.java
  src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
  src/main/java/com/project/foradhd/domain/board/web/dto/response/CommentListResponseDto.java
  src/main/java/com/project/foradhd/domain/board/web/dto/response/PostListResponseDto.java
  src/main/java/com/project/foradhd/domain/board/web/mapper/CommentMapper.java
  src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java
Labels: D-3

#120 fix: 이메일 허용 도메인 수정
  src/main/java/com/project/foradhd/global/validation/validator/EmailDomainValidator.java
  src/main/java/com/project/foradhd/global/validation/validator/EmailValidator.java
Labels: D-2

#137 dto/in/ReportPostData 폴더 이동 및 신고 처리 기능 400 에러 해결
  src/main/java/com/project/foradhd/domain/board/business/dto/in/ReportPostData.java
  src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
  src/main/java/com/project/foradhd/domain/board/web/dto/request/HandleReportRequest.java
  src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java
Labels: D-0

#130 차단된 유저의 게시물 서버에서 필터링 후 반환
  .DS_Store
  src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
Labels: D-2

#140 mod: custom exception 구현 및 의약품 쿼리 수정
  build.gradle
  src/main/java/com/project/foradhd/domain/board/business/service/CommentService.java
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostLikeFilterServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostScrapFilterServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/persistence/repository/CommentRepository.java
  src/main/java/com/project/foradhd/domain/board/persistence/repository/PostRepository.java
  src/main/java/com/project/foradhd/domain/board/web/controller/CommentController.java
  src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
  src/main/java/com/project/foradhd/domain/medicine/business/service/impl/MedicineServiceImpl.java
  src/main/java/com/project/foradhd/domain/medicine/persistence/repository/MedicineRepository.java
  src/main/java/com/project/foradhd/domain/user/persistence/entity/User.java
Labels: D-2

#142 약 스크랩 시 isFavorite 필드 에러 수정
  src/main/java/com/project/foradhd/domain/medicine/business/service/MedicineService.java
  src/main/java/com/project/foradhd/domain/medicine/business/service/impl/MedicineServiceImpl.java
  src/main/java/com/project/foradhd/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/project/foradhd/domain/medicine/web/dto/response/MedicineBookmarkResponse.java
  src/main/java/com/project/foradhd/domain/medicine/web/mapper/MedicineMapper.java
Labels: D-1

#151 feat: 비밀번호 변경 시 기존 비밀번호랑 동일할 경우 에러 처리
  src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java
  src/main/java/com/project/foradhd/global/exception/ErrorCode.java
Labels: D-1

#157 mod: 댓글 soft delete 되도록 수정
  src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java
  src/main/java/com/project/foradhd/domain/board/persistence/entity/Comment.java
  src/main/java/com/project/foradhd/domain/board/persistence/repository/CommentRepository.java
  src/main/java/com/project/foradhd/domain/board/web/dto/response/CommentListResponseDto.java
  src/main/java/com/project/foradhd/domain/board/web/mapper/CommentMapper.java
Labels: D-3
